services:

  postgres:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}'"]
      interval: 3s
      timeout: 30s
      retries: 10
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres2:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}'"]
      interval: 3s
      timeout: 30s
      retries: 10
    environment:
      POSTGRES_DB: my_db2
      POSTGRES_USER: my_user2
      POSTGRES_PASSWORD: my_pass2
    # volumes:
    #   - postgres-data2:/var/lib/postgresql/data
    restart: unless-stopped

  postgres3:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}'"]
      interval: 3s
      timeout: 30s
      retries: 10
    environment:
      POSTGRES_DB: my_db3
      POSTGRES_USER: my_user3
      POSTGRES_PASSWORD: my_pass3
    # volumes:
    #   - postgres-data3:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    build: ./
    image: dcagatay/pwless-pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
      postgres2:
        condition: service_healthy
      postgres3:
        condition: service_healthy
    ports:
      - 25432:80
    environment:
      POSTGRES_USER_1: my_user
      POSTGRES_PASSWORD_1: my_pass
      # POSTGRES_HOST_1: "postgres"
      # POSTGRES_PORT_1: "5432"
      # POSTGRES_DB_1: "*"

      POSTGRES_USER_2: my_user2
      POSTGRES_PASSWORD_2: my_pass2
      POSTGRES_HOST_2: "postgres2"
      # POSTGRES_PORT_2: "5432"
      # POSTGRES_DB_2: "*"

      POSTGRES_USER_3: my_user3
      POSTGRES_PASSWORD_3: my_pass3
      POSTGRES_HOST_3: "postgres3"
      # POSTGRES_PORT_3: "5432"
      # POSTGRES_DB_3: "*"
    restart: unless-stopped

# volumes:
#   postgres-data:
#   postgres-data2:
#   postgres-data3:
