services:

  postgres:
    image: postgres:alpine
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready --dbname=$${POSTGRES_DB} --username=$${POSTGRES_USER}'"]
      interval: 3s
      timeout: 30s
      retries: 10
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    build: ./
    image: dcagatay/pwless-pgadmin4:latest
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - 15432:80
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
      # POSTGRES_HOST: "postgres"
      # POSTGRES_PORT: "5432"
      # POSTGRES_DB: "*"
    restart: unless-stopped

# volumes:
#   postgres-data:
