version: "3.3"
services:
  postgres:
    image: postgres:13.5-alpine
    environment:
      POSTGRES_DB: my_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
    ports:
      - 5432:5432
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin4:
    build: ./
    image: dcagatay/pwless-pgadmin4:latest
    depends_on:
      - postgres
    ports:
      - 15432:80
    environment:
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
      # POSTGRES_HOST: "postgres"
      # POSTGRES_PORT: "5432"
      # POSTGRES_DB: "*"
    restart: unless-stopped
# volumes:
#   postgres-data:
