name: build-container-image
on:
  workflow_call:
    inputs:
      image_tag:
        required: true
        type: string
      should_push_image:
        default: false
        type: boolean
      should_update_repo_description:
        default: false
        type: boolean


jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ inputs.should_push_image }}
          tags: |
            dcagatay/pwless-pgadmin4:${{ inputs.image_tag }}

      - name: Update Dockerhub description
        if: ${{ inputs.should_update_repo_description }}
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dcagatay/pwless-pgadmin4
