name: build-push-latest-version
on:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - docker-compose.yml
    branches:
      - master
  #  workflow_dispatch:
  #  schedule:
  #    - cron: "30 6 5 * *" # Run monthly for updates

jobs:
  bake-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install gather Azure Devops Agent versions from API
        id: version_provider
        run: |
          VERSION=$(cat Dockerfile | grep 'ARG BASE_VERSION' | awk -F\" '{print $2}')
          echo "::set-output name=version::$VERSION"

      - name: debug
        run: |
          echo "::debug:: ${{steps.version_provider.outputs.version}}"

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            dcagatay/pwless-pgadmin4:latest
            dcagatay/pwless-pgadmin4:${{steps.version_provider.outputs.version}}
