name: build-push-latest-version
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - docker-compose.yml
      - docker-compose-multi.yml
    branches:
      - master

jobs:
  build-push-latest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from Dockerfile
        id: version_provider
        run: |
          VERSION=$(grep 'ARG BASE_VERSION' Dockerfile | awk -F= '{print $2}')
          echo "BASE_CONTAINER_VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: debug
        run: |
          echo "::debug:: ${{ env.BASE_CONTAINER_VERSION }}"

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: |
            dcagatay/pwless-pgadmin4:latest
          tags: |
            dcagatay/pwless-pgadmin4:latest
            dcagatay/pwless-pgadmin4:${{ env.BASE_CONTAINER_VERSION }}

      - name: Update repo description
        uses: peter-evans/dockerhub-description@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: dcagatay/pwless-pgadmin4
