name: build-latest-image-on-master
on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
      - LICENSE
      - compose.yml
      - compose-multi.yml
    branches:
      - master
      - main

jobs:
  build-and-push-latest-image:
    uses: ./.github/workflows/build-image.yml
    with:
      image_tag: latest
      should_push_image: true
      should_update_repo_description: true
    secrets: inherit

