name: build-on-pull-request
on:
  pull_request:

jobs:
  build-pr-image:
    uses: ./.github/workflows/build-image.yml
    with:
      image_tag: pr-${{ github.event.pull_request.number }}
    secrets: inherit
