name: build-on-pull-request
on:
  pull_request:

jobs:
  build-image:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Get version from Dockerfile
        id: version_provider
        run: |
          VERSION=$(grep 'ARG BASE_VERSION' Dockerfile | awk -F= '{print $2}')
          echo "BASE_CONTAINER_VERSION=$VERSION"

      - name: Build (no push)
        uses: docker/build-push-action@v5
        with:
          platforms: linux/amd64,linux/arm64
          push: false
          tags: |
            dcagatay/pwless-pgadmin4:pr-${{ github.event.pull_request.number }}
